/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WhatsappMessagesRouteImport } from './routes/whatsapp-messages'
import { Route as SmartAgentRouteImport } from './routes/smart-agent'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as RebrandStudioRouteImport } from './routes/rebrand-studio'
import { Route as PromptVaultRouteImport } from './routes/prompt-vault'
import { Route as PartnerProfileRouteImport } from './routes/partner-profile'
import { Route as MyOrdersRouteImport } from './routes/my-orders'
import { Route as MyCreativesRouteImport } from './routes/my-creatives'
import { Route as MarketingPackRouteImport } from './routes/marketing-pack'
import { Route as MarketingGuideRouteImport } from './routes/marketing-guide'
import { Route as LogoutRouteImport } from './routes/logout'
import { Route as HashtagGeneratorRouteImport } from './routes/hashtag-generator'
import { Route as EarningsRouteImport } from './routes/earnings'
import { Route as DownloadsRouteImport } from './routes/downloads'
import { Route as CreativeLibraryRouteImport } from './routes/creative-library'
import { Route as CommissionsRouteImport } from './routes/commissions'
import { Route as CaptionGeneratorRouteImport } from './routes/caption-generator'
import { Route as BuildBrandRouteImport } from './routes/build-brand'
import { Route as B2bRatesRouteImport } from './routes/b2b-rates'
import { Route as AiMarketingLabRouteImport } from './routes/ai-marketing-lab'
import { Route as AiLabRouteImport } from './routes/ai-lab'
import { Route as AiImageGeneratorRouteImport } from './routes/ai-image-generator'
import { Route as AiImageEditorRouteImport } from './routes/ai-image-editor'
import { Route as AiCreativeLabRouteImport } from './routes/ai-creative-lab'
import { Route as AiAudioLabRouteImport } from './routes/ai-audio-lab'
import { Route as AiAssistantCenterRouteImport } from './routes/ai-assistant-center'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AdCopyRouteImport } from './routes/ad-copy'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthResetPasswordRouteImport } from './routes/auth.reset-password'
import { Route as AuthRegisterRouteImport } from './routes/auth.register'
import { Route as AuthLoginRouteImport } from './routes/auth.login'
import { Route as AuthForgotPasswordRouteImport } from './routes/auth.forgot-password'
import { Route as ApiGenerateImageRouteImport } from './routes/api/generate-image'
import { Route as ApiEditImageRouteImport } from './routes/api/edit-image'

const WhatsappMessagesRoute = WhatsappMessagesRouteImport.update({
  id: '/whatsapp-messages',
  path: '/whatsapp-messages',
  getParentRoute: () => rootRouteImport,
} as any)
const SmartAgentRoute = SmartAgentRouteImport.update({
  id: '/smart-agent',
  path: '/smart-agent',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const RebrandStudioRoute = RebrandStudioRouteImport.update({
  id: '/rebrand-studio',
  path: '/rebrand-studio',
  getParentRoute: () => rootRouteImport,
} as any)
const PromptVaultRoute = PromptVaultRouteImport.update({
  id: '/prompt-vault',
  path: '/prompt-vault',
  getParentRoute: () => rootRouteImport,
} as any)
const PartnerProfileRoute = PartnerProfileRouteImport.update({
  id: '/partner-profile',
  path: '/partner-profile',
  getParentRoute: () => rootRouteImport,
} as any)
const MyOrdersRoute = MyOrdersRouteImport.update({
  id: '/my-orders',
  path: '/my-orders',
  getParentRoute: () => rootRouteImport,
} as any)
const MyCreativesRoute = MyCreativesRouteImport.update({
  id: '/my-creatives',
  path: '/my-creatives',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketingPackRoute = MarketingPackRouteImport.update({
  id: '/marketing-pack',
  path: '/marketing-pack',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketingGuideRoute = MarketingGuideRouteImport.update({
  id: '/marketing-guide',
  path: '/marketing-guide',
  getParentRoute: () => rootRouteImport,
} as any)
const LogoutRoute = LogoutRouteImport.update({
  id: '/logout',
  path: '/logout',
  getParentRoute: () => rootRouteImport,
} as any)
const HashtagGeneratorRoute = HashtagGeneratorRouteImport.update({
  id: '/hashtag-generator',
  path: '/hashtag-generator',
  getParentRoute: () => rootRouteImport,
} as any)
const EarningsRoute = EarningsRouteImport.update({
  id: '/earnings',
  path: '/earnings',
  getParentRoute: () => rootRouteImport,
} as any)
const DownloadsRoute = DownloadsRouteImport.update({
  id: '/downloads',
  path: '/downloads',
  getParentRoute: () => rootRouteImport,
} as any)
const CreativeLibraryRoute = CreativeLibraryRouteImport.update({
  id: '/creative-library',
  path: '/creative-library',
  getParentRoute: () => rootRouteImport,
} as any)
const CommissionsRoute = CommissionsRouteImport.update({
  id: '/commissions',
  path: '/commissions',
  getParentRoute: () => rootRouteImport,
} as any)
const CaptionGeneratorRoute = CaptionGeneratorRouteImport.update({
  id: '/caption-generator',
  path: '/caption-generator',
  getParentRoute: () => rootRouteImport,
} as any)
const BuildBrandRoute = BuildBrandRouteImport.update({
  id: '/build-brand',
  path: '/build-brand',
  getParentRoute: () => rootRouteImport,
} as any)
const B2bRatesRoute = B2bRatesRouteImport.update({
  id: '/b2b-rates',
  path: '/b2b-rates',
  getParentRoute: () => rootRouteImport,
} as any)
const AiMarketingLabRoute = AiMarketingLabRouteImport.update({
  id: '/ai-marketing-lab',
  path: '/ai-marketing-lab',
  getParentRoute: () => rootRouteImport,
} as any)
const AiLabRoute = AiLabRouteImport.update({
  id: '/ai-lab',
  path: '/ai-lab',
  getParentRoute: () => rootRouteImport,
} as any)
const AiImageGeneratorRoute = AiImageGeneratorRouteImport.update({
  id: '/ai-image-generator',
  path: '/ai-image-generator',
  getParentRoute: () => rootRouteImport,
} as any)
const AiImageEditorRoute = AiImageEditorRouteImport.update({
  id: '/ai-image-editor',
  path: '/ai-image-editor',
  getParentRoute: () => rootRouteImport,
} as any)
const AiCreativeLabRoute = AiCreativeLabRouteImport.update({
  id: '/ai-creative-lab',
  path: '/ai-creative-lab',
  getParentRoute: () => rootRouteImport,
} as any)
const AiAudioLabRoute = AiAudioLabRouteImport.update({
  id: '/ai-audio-lab',
  path: '/ai-audio-lab',
  getParentRoute: () => rootRouteImport,
} as any)
const AiAssistantCenterRoute = AiAssistantCenterRouteImport.update({
  id: '/ai-assistant-center',
  path: '/ai-assistant-center',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AdCopyRoute = AdCopyRouteImport.update({
  id: '/ad-copy',
  path: '/ad-copy',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthResetPasswordRoute = AuthResetPasswordRouteImport.update({
  id: '/auth/reset-password',
  path: '/auth/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRegisterRoute = AuthRegisterRouteImport.update({
  id: '/auth/register',
  path: '/auth/register',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthForgotPasswordRoute = AuthForgotPasswordRouteImport.update({
  id: '/auth/forgot-password',
  path: '/auth/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGenerateImageRoute = ApiGenerateImageRouteImport.update({
  id: '/api/generate-image',
  path: '/api/generate-image',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiEditImageRoute = ApiEditImageRouteImport.update({
  id: '/api/edit-image',
  path: '/api/edit-image',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ad-copy': typeof AdCopyRoute
  '/admin': typeof AdminRoute
  '/ai-assistant-center': typeof AiAssistantCenterRoute
  '/ai-audio-lab': typeof AiAudioLabRoute
  '/ai-creative-lab': typeof AiCreativeLabRoute
  '/ai-image-editor': typeof AiImageEditorRoute
  '/ai-image-generator': typeof AiImageGeneratorRoute
  '/ai-lab': typeof AiLabRoute
  '/ai-marketing-lab': typeof AiMarketingLabRoute
  '/b2b-rates': typeof B2bRatesRoute
  '/build-brand': typeof BuildBrandRoute
  '/caption-generator': typeof CaptionGeneratorRoute
  '/commissions': typeof CommissionsRoute
  '/creative-library': typeof CreativeLibraryRoute
  '/downloads': typeof DownloadsRoute
  '/earnings': typeof EarningsRoute
  '/hashtag-generator': typeof HashtagGeneratorRoute
  '/logout': typeof LogoutRoute
  '/marketing-guide': typeof MarketingGuideRoute
  '/marketing-pack': typeof MarketingPackRoute
  '/my-creatives': typeof MyCreativesRoute
  '/my-orders': typeof MyOrdersRoute
  '/partner-profile': typeof PartnerProfileRoute
  '/prompt-vault': typeof PromptVaultRoute
  '/rebrand-studio': typeof RebrandStudioRoute
  '/services': typeof ServicesRoute
  '/settings': typeof SettingsRoute
  '/smart-agent': typeof SmartAgentRoute
  '/whatsapp-messages': typeof WhatsappMessagesRoute
  '/api/edit-image': typeof ApiEditImageRoute
  '/api/generate-image': typeof ApiGenerateImageRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ad-copy': typeof AdCopyRoute
  '/admin': typeof AdminRoute
  '/ai-assistant-center': typeof AiAssistantCenterRoute
  '/ai-audio-lab': typeof AiAudioLabRoute
  '/ai-creative-lab': typeof AiCreativeLabRoute
  '/ai-image-editor': typeof AiImageEditorRoute
  '/ai-image-generator': typeof AiImageGeneratorRoute
  '/ai-lab': typeof AiLabRoute
  '/ai-marketing-lab': typeof AiMarketingLabRoute
  '/b2b-rates': typeof B2bRatesRoute
  '/build-brand': typeof BuildBrandRoute
  '/caption-generator': typeof CaptionGeneratorRoute
  '/commissions': typeof CommissionsRoute
  '/creative-library': typeof CreativeLibraryRoute
  '/downloads': typeof DownloadsRoute
  '/earnings': typeof EarningsRoute
  '/hashtag-generator': typeof HashtagGeneratorRoute
  '/logout': typeof LogoutRoute
  '/marketing-guide': typeof MarketingGuideRoute
  '/marketing-pack': typeof MarketingPackRoute
  '/my-creatives': typeof MyCreativesRoute
  '/my-orders': typeof MyOrdersRoute
  '/partner-profile': typeof PartnerProfileRoute
  '/prompt-vault': typeof PromptVaultRoute
  '/rebrand-studio': typeof RebrandStudioRoute
  '/services': typeof ServicesRoute
  '/settings': typeof SettingsRoute
  '/smart-agent': typeof SmartAgentRoute
  '/whatsapp-messages': typeof WhatsappMessagesRoute
  '/api/edit-image': typeof ApiEditImageRoute
  '/api/generate-image': typeof ApiGenerateImageRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ad-copy': typeof AdCopyRoute
  '/admin': typeof AdminRoute
  '/ai-assistant-center': typeof AiAssistantCenterRoute
  '/ai-audio-lab': typeof AiAudioLabRoute
  '/ai-creative-lab': typeof AiCreativeLabRoute
  '/ai-image-editor': typeof AiImageEditorRoute
  '/ai-image-generator': typeof AiImageGeneratorRoute
  '/ai-lab': typeof AiLabRoute
  '/ai-marketing-lab': typeof AiMarketingLabRoute
  '/b2b-rates': typeof B2bRatesRoute
  '/build-brand': typeof BuildBrandRoute
  '/caption-generator': typeof CaptionGeneratorRoute
  '/commissions': typeof CommissionsRoute
  '/creative-library': typeof CreativeLibraryRoute
  '/downloads': typeof DownloadsRoute
  '/earnings': typeof EarningsRoute
  '/hashtag-generator': typeof HashtagGeneratorRoute
  '/logout': typeof LogoutRoute
  '/marketing-guide': typeof MarketingGuideRoute
  '/marketing-pack': typeof MarketingPackRoute
  '/my-creatives': typeof MyCreativesRoute
  '/my-orders': typeof MyOrdersRoute
  '/partner-profile': typeof PartnerProfileRoute
  '/prompt-vault': typeof PromptVaultRoute
  '/rebrand-studio': typeof RebrandStudioRoute
  '/services': typeof ServicesRoute
  '/settings': typeof SettingsRoute
  '/smart-agent': typeof SmartAgentRoute
  '/whatsapp-messages': typeof WhatsappMessagesRoute
  '/api/edit-image': typeof ApiEditImageRoute
  '/api/generate-image': typeof ApiGenerateImageRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/ad-copy'
    | '/admin'
    | '/ai-assistant-center'
    | '/ai-audio-lab'
    | '/ai-creative-lab'
    | '/ai-image-editor'
    | '/ai-image-generator'
    | '/ai-lab'
    | '/ai-marketing-lab'
    | '/b2b-rates'
    | '/build-brand'
    | '/caption-generator'
    | '/commissions'
    | '/creative-library'
    | '/downloads'
    | '/earnings'
    | '/hashtag-generator'
    | '/logout'
    | '/marketing-guide'
    | '/marketing-pack'
    | '/my-creatives'
    | '/my-orders'
    | '/partner-profile'
    | '/prompt-vault'
    | '/rebrand-studio'
    | '/services'
    | '/settings'
    | '/smart-agent'
    | '/whatsapp-messages'
    | '/api/edit-image'
    | '/api/generate-image'
    | '/auth/forgot-password'
    | '/auth/login'
    | '/auth/register'
    | '/auth/reset-password'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/ad-copy'
    | '/admin'
    | '/ai-assistant-center'
    | '/ai-audio-lab'
    | '/ai-creative-lab'
    | '/ai-image-editor'
    | '/ai-image-generator'
    | '/ai-lab'
    | '/ai-marketing-lab'
    | '/b2b-rates'
    | '/build-brand'
    | '/caption-generator'
    | '/commissions'
    | '/creative-library'
    | '/downloads'
    | '/earnings'
    | '/hashtag-generator'
    | '/logout'
    | '/marketing-guide'
    | '/marketing-pack'
    | '/my-creatives'
    | '/my-orders'
    | '/partner-profile'
    | '/prompt-vault'
    | '/rebrand-studio'
    | '/services'
    | '/settings'
    | '/smart-agent'
    | '/whatsapp-messages'
    | '/api/edit-image'
    | '/api/generate-image'
    | '/auth/forgot-password'
    | '/auth/login'
    | '/auth/register'
    | '/auth/reset-password'
  id:
    | '__root__'
    | '/'
    | '/ad-copy'
    | '/admin'
    | '/ai-assistant-center'
    | '/ai-audio-lab'
    | '/ai-creative-lab'
    | '/ai-image-editor'
    | '/ai-image-generator'
    | '/ai-lab'
    | '/ai-marketing-lab'
    | '/b2b-rates'
    | '/build-brand'
    | '/caption-generator'
    | '/commissions'
    | '/creative-library'
    | '/downloads'
    | '/earnings'
    | '/hashtag-generator'
    | '/logout'
    | '/marketing-guide'
    | '/marketing-pack'
    | '/my-creatives'
    | '/my-orders'
    | '/partner-profile'
    | '/prompt-vault'
    | '/rebrand-studio'
    | '/services'
    | '/settings'
    | '/smart-agent'
    | '/whatsapp-messages'
    | '/api/edit-image'
    | '/api/generate-image'
    | '/auth/forgot-password'
    | '/auth/login'
    | '/auth/register'
    | '/auth/reset-password'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdCopyRoute: typeof AdCopyRoute
  AdminRoute: typeof AdminRoute
  AiAssistantCenterRoute: typeof AiAssistantCenterRoute
  AiAudioLabRoute: typeof AiAudioLabRoute
  AiCreativeLabRoute: typeof AiCreativeLabRoute
  AiImageEditorRoute: typeof AiImageEditorRoute
  AiImageGeneratorRoute: typeof AiImageGeneratorRoute
  AiLabRoute: typeof AiLabRoute
  AiMarketingLabRoute: typeof AiMarketingLabRoute
  B2bRatesRoute: typeof B2bRatesRoute
  BuildBrandRoute: typeof BuildBrandRoute
  CaptionGeneratorRoute: typeof CaptionGeneratorRoute
  CommissionsRoute: typeof CommissionsRoute
  CreativeLibraryRoute: typeof CreativeLibraryRoute
  DownloadsRoute: typeof DownloadsRoute
  EarningsRoute: typeof EarningsRoute
  HashtagGeneratorRoute: typeof HashtagGeneratorRoute
  LogoutRoute: typeof LogoutRoute
  MarketingGuideRoute: typeof MarketingGuideRoute
  MarketingPackRoute: typeof MarketingPackRoute
  MyCreativesRoute: typeof MyCreativesRoute
  MyOrdersRoute: typeof MyOrdersRoute
  PartnerProfileRoute: typeof PartnerProfileRoute
  PromptVaultRoute: typeof PromptVaultRoute
  RebrandStudioRoute: typeof RebrandStudioRoute
  ServicesRoute: typeof ServicesRoute
  SettingsRoute: typeof SettingsRoute
  SmartAgentRoute: typeof SmartAgentRoute
  WhatsappMessagesRoute: typeof WhatsappMessagesRoute
  ApiEditImageRoute: typeof ApiEditImageRoute
  ApiGenerateImageRoute: typeof ApiGenerateImageRoute
  AuthForgotPasswordRoute: typeof AuthForgotPasswordRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthRegisterRoute: typeof AuthRegisterRoute
  AuthResetPasswordRoute: typeof AuthResetPasswordRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/whatsapp-messages': {
      id: '/whatsapp-messages'
      path: '/whatsapp-messages'
      fullPath: '/whatsapp-messages'
      preLoaderRoute: typeof WhatsappMessagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/smart-agent': {
      id: '/smart-agent'
      path: '/smart-agent'
      fullPath: '/smart-agent'
      preLoaderRoute: typeof SmartAgentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rebrand-studio': {
      id: '/rebrand-studio'
      path: '/rebrand-studio'
      fullPath: '/rebrand-studio'
      preLoaderRoute: typeof RebrandStudioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prompt-vault': {
      id: '/prompt-vault'
      path: '/prompt-vault'
      fullPath: '/prompt-vault'
      preLoaderRoute: typeof PromptVaultRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/partner-profile': {
      id: '/partner-profile'
      path: '/partner-profile'
      fullPath: '/partner-profile'
      preLoaderRoute: typeof PartnerProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-orders': {
      id: '/my-orders'
      path: '/my-orders'
      fullPath: '/my-orders'
      preLoaderRoute: typeof MyOrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-creatives': {
      id: '/my-creatives'
      path: '/my-creatives'
      fullPath: '/my-creatives'
      preLoaderRoute: typeof MyCreativesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marketing-pack': {
      id: '/marketing-pack'
      path: '/marketing-pack'
      fullPath: '/marketing-pack'
      preLoaderRoute: typeof MarketingPackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marketing-guide': {
      id: '/marketing-guide'
      path: '/marketing-guide'
      fullPath: '/marketing-guide'
      preLoaderRoute: typeof MarketingGuideRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/logout': {
      id: '/logout'
      path: '/logout'
      fullPath: '/logout'
      preLoaderRoute: typeof LogoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hashtag-generator': {
      id: '/hashtag-generator'
      path: '/hashtag-generator'
      fullPath: '/hashtag-generator'
      preLoaderRoute: typeof HashtagGeneratorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/earnings': {
      id: '/earnings'
      path: '/earnings'
      fullPath: '/earnings'
      preLoaderRoute: typeof EarningsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/downloads': {
      id: '/downloads'
      path: '/downloads'
      fullPath: '/downloads'
      preLoaderRoute: typeof DownloadsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/creative-library': {
      id: '/creative-library'
      path: '/creative-library'
      fullPath: '/creative-library'
      preLoaderRoute: typeof CreativeLibraryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/commissions': {
      id: '/commissions'
      path: '/commissions'
      fullPath: '/commissions'
      preLoaderRoute: typeof CommissionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/caption-generator': {
      id: '/caption-generator'
      path: '/caption-generator'
      fullPath: '/caption-generator'
      preLoaderRoute: typeof CaptionGeneratorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/build-brand': {
      id: '/build-brand'
      path: '/build-brand'
      fullPath: '/build-brand'
      preLoaderRoute: typeof BuildBrandRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/b2b-rates': {
      id: '/b2b-rates'
      path: '/b2b-rates'
      fullPath: '/b2b-rates'
      preLoaderRoute: typeof B2bRatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-marketing-lab': {
      id: '/ai-marketing-lab'
      path: '/ai-marketing-lab'
      fullPath: '/ai-marketing-lab'
      preLoaderRoute: typeof AiMarketingLabRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-lab': {
      id: '/ai-lab'
      path: '/ai-lab'
      fullPath: '/ai-lab'
      preLoaderRoute: typeof AiLabRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-image-generator': {
      id: '/ai-image-generator'
      path: '/ai-image-generator'
      fullPath: '/ai-image-generator'
      preLoaderRoute: typeof AiImageGeneratorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-image-editor': {
      id: '/ai-image-editor'
      path: '/ai-image-editor'
      fullPath: '/ai-image-editor'
      preLoaderRoute: typeof AiImageEditorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-creative-lab': {
      id: '/ai-creative-lab'
      path: '/ai-creative-lab'
      fullPath: '/ai-creative-lab'
      preLoaderRoute: typeof AiCreativeLabRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-audio-lab': {
      id: '/ai-audio-lab'
      path: '/ai-audio-lab'
      fullPath: '/ai-audio-lab'
      preLoaderRoute: typeof AiAudioLabRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-assistant-center': {
      id: '/ai-assistant-center'
      path: '/ai-assistant-center'
      fullPath: '/ai-assistant-center'
      preLoaderRoute: typeof AiAssistantCenterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ad-copy': {
      id: '/ad-copy'
      path: '/ad-copy'
      fullPath: '/ad-copy'
      preLoaderRoute: typeof AdCopyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/reset-password': {
      id: '/auth/reset-password'
      path: '/auth/reset-password'
      fullPath: '/auth/reset-password'
      preLoaderRoute: typeof AuthResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/register': {
      id: '/auth/register'
      path: '/auth/register'
      fullPath: '/auth/register'
      preLoaderRoute: typeof AuthRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/forgot-password': {
      id: '/auth/forgot-password'
      path: '/auth/forgot-password'
      fullPath: '/auth/forgot-password'
      preLoaderRoute: typeof AuthForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/generate-image': {
      id: '/api/generate-image'
      path: '/api/generate-image'
      fullPath: '/api/generate-image'
      preLoaderRoute: typeof ApiGenerateImageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/edit-image': {
      id: '/api/edit-image'
      path: '/api/edit-image'
      fullPath: '/api/edit-image'
      preLoaderRoute: typeof ApiEditImageRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdCopyRoute: AdCopyRoute,
  AdminRoute: AdminRoute,
  AiAssistantCenterRoute: AiAssistantCenterRoute,
  AiAudioLabRoute: AiAudioLabRoute,
  AiCreativeLabRoute: AiCreativeLabRoute,
  AiImageEditorRoute: AiImageEditorRoute,
  AiImageGeneratorRoute: AiImageGeneratorRoute,
  AiLabRoute: AiLabRoute,
  AiMarketingLabRoute: AiMarketingLabRoute,
  B2bRatesRoute: B2bRatesRoute,
  BuildBrandRoute: BuildBrandRoute,
  CaptionGeneratorRoute: CaptionGeneratorRoute,
  CommissionsRoute: CommissionsRoute,
  CreativeLibraryRoute: CreativeLibraryRoute,
  DownloadsRoute: DownloadsRoute,
  EarningsRoute: EarningsRoute,
  HashtagGeneratorRoute: HashtagGeneratorRoute,
  LogoutRoute: LogoutRoute,
  MarketingGuideRoute: MarketingGuideRoute,
  MarketingPackRoute: MarketingPackRoute,
  MyCreativesRoute: MyCreativesRoute,
  MyOrdersRoute: MyOrdersRoute,
  PartnerProfileRoute: PartnerProfileRoute,
  PromptVaultRoute: PromptVaultRoute,
  RebrandStudioRoute: RebrandStudioRoute,
  ServicesRoute: ServicesRoute,
  SettingsRoute: SettingsRoute,
  SmartAgentRoute: SmartAgentRoute,
  WhatsappMessagesRoute: WhatsappMessagesRoute,
  ApiEditImageRoute: ApiEditImageRoute,
  ApiGenerateImageRoute: ApiGenerateImageRoute,
  AuthForgotPasswordRoute: AuthForgotPasswordRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthRegisterRoute: AuthRegisterRoute,
  AuthResetPasswordRoute: AuthResetPasswordRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
